# Generated by Django 5.2.5 on 2026-01-16 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử thuê số', 'verbose_name_plural': 'Quản lý thuê số'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Ví người dùng', 'verbose_name_plural': 'Quản lý ví tiền'},
        ),
        migrations.AddField(
            model_name='rentsession',
            name='sms_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='original_price',
            field=models.IntegerField(default=0, help_text='Giá gốc nhập vào'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='otp_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã OTP'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='request_id',
            field=models.CharField(max_length=50, verbose_name='Mã Request ID'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='sell_price',
            field=models.IntegerField(default=0, help_text='Giá bán cho khách'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Đang chờ'), ('Success', 'Thành công'), ('Expired', 'Hết hạn')], default='Waiting', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='rentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
